import {
	Building,
	BuildingApartment,
	BuildingOffice,
	Buildings,
	City,
	Hexagon,
	MapTrifold,
	Scales,
	Shapes,
	Tag,
	TextT,
	Truck,
	Warehouse,
	Wrench,
} from "@phosphor-icons/react";
import { TModule } from "./modules";

export type TMETAMODULE = Record<string, TModule>;

export const METAMODULES: TMETAMODULE = {
	COMPANIES: {
		ALIAS: "Companies",
		KEY: "companies",
		PATH: "/companies",
		ICON: <BuildingOffice />,
		ICON_ON: <BuildingOffice weight="fill" />,
		DESCRIPTION: "Manage organization entities and company profiles.",
	},
	BUSINESS_UNITS: {
		ALIAS: "Business Units",
		KEY: "business_units",
		PATH: "/business-units",
		ICON: <Building />,
		ICON_ON: <Building weight="fill" />,
		DESCRIPTION: "Organize and manage top-level operational divisions.",
	},
	DEPARTMENTS: {
		ALIAS: "Departments",
		KEY: "departments",
		PATH: "/departments",
		ICON: <BuildingApartment />,
		ICON_ON: <BuildingApartment weight="fill" />,
		DESCRIPTION: "Configure functional departments within business units.",
	},
	DEPARTMENT_UNITS: {
		ALIAS: "Units",
		KEY: "units",
		PATH: "/units",
		ICON: <Buildings />,
		ICON_ON: <Buildings weight="fill" />,
		DESCRIPTION: "Manage specialized units within departments.",
	},
	SUB_UNITS: {
		ALIAS: "Sub-Units",
		KEY: "sub_units",
		PATH: "/sub-units",
		ICON: <City />,
		ICON_ON: <City weight="fill" />,
		DESCRIPTION: "Define granular operational groups within department units.",
	},
	LOCATIONS: {
		ALIAS: "Locations",
		KEY: "locations",
		PATH: "/locations",
		ICON: <MapTrifold />,
		ICON_ON: <MapTrifold weight="fill" />,
		DESCRIPTION: "Manage physical locations and geographic information.",
	},
	WAREHOUSES: {
		ALIAS: "Warehouses",
		KEY: "warehouses",
		PATH: "/warehouses",
		ICON: <Warehouse />,
		ICON_ON: <Warehouse weight="fill" />,
		DESCRIPTION: "Configure storage facilities and inventory locations.",
	},
	UOM: {
		ALIAS: "UOM",
		KEY: "uom",
		PATH: "/uom",
		ICON: <Scales />,
		ICON_ON: <Scales weight="fill" />,
		DESCRIPTION: "Define and manage Units of Measurement for inventory items.",
	},
	CATEGORIES: {
		ALIAS: "Categories",
		KEY: "categories",
		PATH: "/categories",
		ICON: <Shapes />,
		ICON_ON: <Shapes weight="fill" />,
		DESCRIPTION: "Organize items through classification categories.",
	},
	TYPES: {
		ALIAS: "Types",
		KEY: "types",
		PATH: "/types",
		ICON: <TextT />,
		ICON_ON: <TextT weight="fill" />,
		DESCRIPTION: "Define specific types and classifications for system entities.",
	},
	SUPPLIERS: {
		ALIAS: "Suppliers",
		KEY: "suppliers",
		PATH: "/suppliers",
		ICON: <Truck />,
		ICON_ON: <Truck weight="fill" />,
		DESCRIPTION: "Manage vendor information and supplier relationships.",
	},
	ITEMS: {
		ALIAS: "Items",
		KEY: "items",
		PATH: "/items",
		ICON: <Hexagon />,
		ICON_ON: <Hexagon weight="fill" />,
		DESCRIPTION: "Catalog and manage inventory and product items.",
	},
	SMALL_TOOLS: {
		ALIAS: "Small Tools",
		KEY: "small_tools",
		PATH: "/small-tools",
		ICON: <Wrench />,
		ICON_ON: <Wrench weight="fill" />,
		DESCRIPTION: "Track and manage smaller equipment and tools inventory.",
	},
	ASSET_TAGS: {
		ALIAS: "Asset Tags",
		KEY: "asset_tags",
		PATH: "/asset-tags",
		ICON: <Tag />,
		ICON_ON: <Tag weight="fill" />,
		DESCRIPTION: "Assign and manage identification tags for physical assets.",
	},
} as const;
export type TMetaModuleKey = keyof typeof METAMODULES;
