import { createSlice, PayloadAction } from "@reduxjs/toolkit";
import { persistReducer } from "redux-persist";
import storage from "redux-persist/lib/storage";
const initialState = {
  touchedData: {
    isForApproving: false,
    isViewing: false,
    id: 0,
    code: "",
    name: "",
    month: "",
    year: "",
    week: "",
    store_checklist: [
      {
        id: 0,
        code: "",
        checklist: {
          id: 0,
          name: "",
          created_at: "",
          updated_at: "",
          deleted_at: null,
        },
        sections: [
          {
            id: 0,
            checklist_id: 0,
            title: "",
            description: null,
            order_index: 0,
            questions: [
              {
                id: 0,
                section_id: 0,
                question_type: "multiple_choice",
                question_text: "",
                order_index: 0,
                options: [
                  {
                    id: 0,
                    question_id: 0,
                    option_text: "",
                    order_index: 0,
                    created_at: "",
                    updated_at: "",
                    deleted_at: null,
                    score_rating_id: 0,
                  },
                ],
                created_at: "",
                updated_at: "",
                deleted_at: null,
              },
            ],
            created_at: "",
            updated_at: "",
            deleted_at: null,
          },
        ],
        weekly_record: [
          {
            id: 0,
            store_checklist_id: 0,
            week: 0,
            month: 0,
            year: 0,
            weekly_grade: "",
            status: "",
            weekly_skipped: {
              id: 0,
              weekly_id: 0,
              week: 0,
              month: 0,
              year: 0,
              approver_id: 0,
              approver_name: "",
              approved_at: null,
              rejected_at: null,
              created_at: "",
              updated_at: "",
              deleted_at: null,
            },
            is_auto_grade: false,
            grade_source: "",
            graded_by: 0,
            grade_notes: null,
            store_visit: null,
            expired: null,
            condemned: null,
            created_at: "",
            updated_at: "",
            deleted_at: null,
          },
        ],
        created_at: "",
        updated_at: "",
        deleted_at: null,
      },
    ],
    region: {
      id: 0,
      name: "",
    },
    area: {
      id: 0,
      name: "",
    },
    created_at: "",
    updated_at: "",
    deleted_at: null,
  },
  checklistData: {
    isForApproving: false,
    status: "",
    singleWeeklyRecord: [
      {
        id: 0,
        store_checklist_id: 0,
        week: 0,
        month: 0,
        year: 0,
        weekly_grade: "",
        status: "",
        for_approval_reason: "",
        weekly_skipped: {
          id: 0,
          weekly_id: 0,
          week: 0,
          month: 0,
          year: 0,
          approver_id: 0,
          approver_name: "",
          approved_at: null,
          rejected_at: null,
          created_at: "",
          updated_at: "",
          deleted_at: null,
        },
        is_auto_grade: false,
        grade_source: "",
        graded_by: 0,
        grade_notes: null,
        store_visit: null,
        expired: null,
        condemned: null,
        created_at: "",
        updated_at: "",
        deleted_at: null,
      },
    ],
    code: "",
    condemned: "",
    expired: "",
    good_points: "",
    grade: "",
    notes: "",
    store_duty_id: "",
    store_visit: "",
    created_at: "",
    deleted_at: "",
    updated_at: "",
    sections: [
      {
        id: 0,
        checklist_id: 0,
        title: "",
        description: "",
        order_index: 0,
        questions: [
          {
            id: 0,
            section_id: 0,
            question_type: "multiple_choice",
            question_text: "",
            order_index: 0,
            options: [
              {
                id: 0,
                question_id: 0,
                option_text: "",
                order_index: 0,
                created_at: "",
                updated_at: "",
                deleted_at: "",
              },
            ],
          },
        ],
      },
    ],
    isOverdue: false,
    isViewStoreChecklist: false,
    isOverdueFillup: false,
    store: "",
    week: "",
    done_on: "",
    qaItemData: {
      week: "",
      done_on: "",
      id: 0,
      name: "",
      region: {
        id: 0,
        name: "",
      },
      area_head: {
        id: 0,
        full_name: "",
        user_status: "",
      },
      store: {
        id: 0,
        code: "",
        name: "",
        checklist: [
          {
            id: 0,
            checklist: "",
            weekly_record: [
              {
                id: 0,
                store_checklist_id: 0,
                week: 0,
                month: 0,
                year: 0,
                weekly_grade: "",
                status: "",
                weekly_skipped: {
                  id: 0,
                  weekly_id: 0,
                  week: 0,
                  month: 0,
                  year: 0,
                  approver_id: 0,
                  approver_name: "",
                  approved_at: null,
                  rejected_at: null,
                  created_at: "",
                  updated_at: "",
                  deleted_at: null,
                },
                is_auto_grade: false,
                grade_source: "",
                graded_by: 0,
                grade_notes: null,
                store_visit: null,
                expired: null,
                condemned: null,
                created_at: "",
                updated_at: "",
                deleted_at: null,
              },
            ],
            code: "",
            condemned: "",
            expired: "",
            good_points: "",
            grade: "",
            notes: "",
            status: "",
            store_duty_id: "",
            store_visit: "",
            created_at: "",
            deleted_at: "",
            updated_at: "",
            sections: [
              {
                id: 0,
                checklist_id: 0,
                title: "",
                description: "",
                order_index: 0,
                questions: [
                  {
                    id: 0,
                    section_id: 0,
                    question_type: "multiple_choice",
                    question_text: "",
                    order_index: 0,
                    options: [
                      {
                        id: 0,
                        question_id: 0,
                        option_text: "",
                        order_index: 0,
                        created_at: "",
                        updated_at: "",
                        deleted_at: "",
                      },
                    ],
                  },
                ],
              },
            ],
          },
        ],
      },
    },
    checklistId: "",
    year: "",
    month: "",
  },
  qaDialog: {
    open: false,
    module: null as string | null,
    reportOpen: false,
  },
};

const qaDashboardPersistConfig = {
  key: "qaDashboard",
  storage,
  whitelist: ["touchedData", "checklistData"], // 👈 ONLY THIS
};

export const qaSlice = createSlice({
  name: "qaSlice",
  initialState,
  reducers: {
    getData: (state, action) => {
      state.touchedData = action.payload.touchedData;
    },
    getChecklistData: (state, action) => {
      state.checklistData = action.payload.checklistData;
    },
    setTouchedData(state, action) {
      state.touchedData = action.payload;
    },
  },
});

// Action creators are generated for each case reducer function
export const { getData, getChecklistData } = qaSlice.actions;

export default persistReducer(qaDashboardPersistConfig, qaSlice.reducer);
